Document: jerasure
Title: Debian jerasure Manual
Author: <insert document author here>
Abstract: This manual describes what jerasure is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jerasure/jerasure.sgml.gz

Format: postscript
Files: /usr/share/doc/jerasure/jerasure.ps.gz

Format: text
Files: /usr/share/doc/jerasure/jerasure.text.gz

Format: HTML
Index: /usr/share/doc/jerasure/html/index.html
Files: /usr/share/doc/jerasure/html/*.html
